# Generated by Django 5.2.7 on 2025-10-04 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocaisProximos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Local')),
                ('description', models.TextField(verbose_name='Descrição do Local')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='media_items.mediaitem')),
            ],
        ),
    ]
