# Generated by Django 5.2.7 on 2025-10-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_uuid'),
    ]

    operations = [
    ]
