# Generated by Django 5.2.7 on 2025-10-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_items', '0001_initial'),
        ('user', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='locais_salvos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_que_salvaram', to='media_items.mediaitem'),
        ),
    ]
