# Generated by Django 5.2.7 on 2025-10-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('media_type', models.CharField(max_length=50, verbose_name='Tipo de Mídia')),
                ('general_info', models.TextField(verbose_name='Informações Gerais')),
                ('opening_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário de Funcionamento')),
                ('location', models.CharField(max_length=255, verbose_name='Localização')),
                ('maps', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link para Mapas')),
                ('autor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor')),
                ('autor_imagem', models.URLField(blank=True, max_length=500, null=True, verbose_name='Imagem do Autor')),
                ('autor_bio', models.TextField(blank=True, null=True, verbose_name='Biografia do Autor')),
                ('obras', models.TextField(blank=True, null=True, verbose_name='Obras')),
                ('autor_link', models.URLField(blank=True, null=True, verbose_name='Link do Autor')),
                ('imagem_cartaz', models.URLField(blank=True, max_length=500, null=True, verbose_name='Imagem de Cartaz')),
                ('legenda_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Legenda 1')),
                ('imagem_obra', models.URLField(blank=True, max_length=500, null=True, verbose_name='Imagem da Obra')),
                ('legenda_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Legenda 2')),
                ('imagem_local', models.URLField(blank=True, max_length=500, null=True, verbose_name='Imagem Local')),
                ('legenda_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Legenda 3')),
                ('outra_imagem1', models.URLField(blank=True, max_length=500, null=True, verbose_name='Outra Imagem 1')),
                ('outra_imagem2', models.URLField(blank=True, max_length=500, null=True, verbose_name='Outra Imagem 2')),
            ],
        ),
    ]
