# Generated by Django 5.2.7 on 2025-10-11 00:49

import conf.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_items', '0002_alter_mediaitem_autor_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='autor_imagem',
            field=models.ImageField(blank=True, null=True, storage=conf.storages.PublicMediaStorage(), upload_to='autores/', verbose_name='Imagem do Autor'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='imagem_cartaz',
            field=models.ImageField(blank=True, null=True, storage=conf.storages.PublicMediaStorage(), upload_to='media/cartazes/', verbose_name='Imagem de Cartaz'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='imagem_local',
            field=models.ImageField(blank=True, null=True, storage=conf.storages.PublicMediaStorage(), upload_to='media/locais/', verbose_name='Imagem Local'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='imagem_obra',
            field=models.ImageField(blank=True, null=True, storage=conf.storages.PublicMediaStorage(), upload_to='media/obras/', verbose_name='Imagem da Obra'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='outra_imagem1',
            field=models.ImageField(blank=True, null=True, storage=conf.storages.PublicMediaStorage(), upload_to='media/outras/', verbose_name='Outra Imagem 1'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='outra_imagem2',
            field=models.ImageField(blank=True, null=True, storage=conf.storages.PublicMediaStorage(), upload_to='media/outras/', verbose_name='Outra Imagem 2'),
        ),
    ]
